whisper:
  model: large # tiny, base, small, medium, large

number_of_clips: 20
target_duration: 35

channels:
  # family_guy:
  #   path: https://www.youtube.com/watch?v=6DmXlJwaP0I
  outdoor_boys:
    path: https://www.youtube.com/watch?v=uSuEdw6HAFE
  